GPU Acceleration Addition
teknoir/bootstrap-device pull request #6
Opened 2023-11-30 15:21 UTC by JMCTek

I have added GPU acceleration by changing the containerd .toml and deploying a runtime class within kubernetes.

This configuration can be set by the USE_GPU_ACCEL=true argument.

Nvidia GPU is accessible immediately after configuration in container environments.

2023-12-06 13:33 UTC, tekn0ir requested changes
I cannot get HW acceleration to work, even if I fiddle with it. How did you test it?

2023-12-06 13:33 UTC, tekn0ir commented on templates/00_tn_header.sh
> +#   USE_GPU_ACCEL=false (default: true, enable or disable the use of GPU acceleration in containerd)
Nowhere in this script is USE_GPU_ACCEL set to true by default.

2023-12-06 13:33 UTC, tekn0ir commented on templates/14_tn_configure_k3s.sh
> +    config_file="/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"
Adding a config.toml.tmpl is not needed according to K3s docs:
https://docs.k3s.io/advanced#nvidia-container-runtime-support

Also, this causes all PODs not to be scheduled after rebooting the system the first time. It does not recover until /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl is deleted.

2023-12-06 13:33 UTC, tekn0ir commented on templates/14_tn_configure_k3s.sh
> +    $SUDO tee "$nvidia_runtimeclass_file" > /dev/null << EOL
I think the RuntimeClass can be added to /var/lib/rancher/k3s/server/manifests/teknoir.yaml instead. That ensures that it is created persistently.

2023-12-07 09:23 UTC, tekn0ir commented
Ok, after deleting the config.toml.tmpl file I was able to get it working!

I added `runtimeClassName: nvidia` to the spec of the Deployments that need HW acceleration like this example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-app-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: object-detection-app-1
  template:
    metadata:
      labels:
        app: object-detection-app-1
    spec:
      runtimeClassName: nvidia
      containers:
        - name: object-detection-app-1
... 
```

But my other comments are still valid. ;-)

2024-02-12 10:01 UTC, closed without merging

2024-02-13 14:05 UTC, muhammadnasr commented
How are you Anders?

I got this email notification from you. Are you sure you removed me from
all github projects?

On Mon, Feb 12, 2024 at 1:01 PM Anders Åslund ***@***.***>
wrote:

> Closed #6 <https://github.com/teknoir/bootstrap-device/pull/6>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/teknoir/bootstrap-device/pull/6#event-11772293396>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABIMCGPU3WO2ZFPUD3H2B3YTHR7DAVCNFSM6AAAAABABLXQ6KVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRG43TEMRZGMZTSNQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-02-13 15:31 UTC, tekn0ir commented
Hi!
All good here! I hope you are well also, sir!

That one is a public repo, so maybe you checked the ”watch repo” so you will be updated on changes?…

//A

> 13 feb. 2024 kl. 15:05 skrev Muhammad Hassan Nasr ***@***.***>:
> 
> 
> How are you Anders? 
> 
> I got this email notification from you. Are you sure you removed me from 
> all github projects? 
> 
> On Mon, Feb 12, 2024 at 1:01 PM Anders Åslund ***@***.***> 
> wrote: 
> 
> > Closed #6 <https://github.com/teknoir/bootstrap-device/pull/6>. 
> > 
> > — 
> > Reply to this email directly, view it on GitHub 
> > <https://github.com/teknoir/bootstrap-device/pull/6#event-11772293396>, 
> > or unsubscribe 
> > <https://github.com/notifications/unsubscribe-auth/AABIMCGPU3WO2ZFPUD3H2B3YTHR7DAVCNFSM6AAAAABABLXQ6KVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRG43TEMRZGMZTSNQ> 
> > . 
> > You are receiving this because you are subscribed to this thread.Message 
> > ID: ***@***.***> 
> >
> —
> Reply to this email directly, view it on GitHub <https://github.com/teknoir/bootstrap-device/pull/6#issuecomment-1941593448>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAVO2EOE2L6G2ME22GCDJNLYTNXJ3AVCNFSM6AAAAABABLXQ6KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBRGU4TGNBUHA>.
> You are receiving this because you modified the open/close state.
>